// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIOjL7ghtU43t50WWLnwq3-POXqkY60Eg',
    appId: '1:599314675360:web:21ec7394330bc0a19b7bc5',
    messagingSenderId: '599314675360',
    projectId: 'edupass-9e2ba',
    authDomain: 'edupass-9e2ba.firebaseapp.com',
    storageBucket: 'edupass-9e2ba.firebasestorage.app',
    measurementId: 'G-RZXMVQDWT4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2vDCf7OwyGguFxvgUfNxMfqh4WfTQwGY',
    appId: '1:599314675360:android:3379f529cca89ae89b7bc5',
    messagingSenderId: '599314675360',
    projectId: 'edupass-9e2ba',
    storageBucket: 'edupass-9e2ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRR79RwMBjq4nCiKJrGaOnYa6RJm3BipA',
    appId: '1:599314675360:ios:233f6b8b72a050e19b7bc5',
    messagingSenderId: '599314675360',
    projectId: 'edupass-9e2ba',
    storageBucket: 'edupass-9e2ba.firebasestorage.app',
    iosClientId: '599314675360-7ggqbj6va616lfgm89phribo6ilg7ba7.apps.googleusercontent.com',
    iosBundleId: 'com.example.edupasss',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRR79RwMBjq4nCiKJrGaOnYa6RJm3BipA',
    appId: '1:599314675360:ios:233f6b8b72a050e19b7bc5',
    messagingSenderId: '599314675360',
    projectId: 'edupass-9e2ba',
    storageBucket: 'edupass-9e2ba.firebasestorage.app',
    iosClientId: '599314675360-7ggqbj6va616lfgm89phribo6ilg7ba7.apps.googleusercontent.com',
    iosBundleId: 'com.example.edupasss',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIOjL7ghtU43t50WWLnwq3-POXqkY60Eg',
    appId: '1:599314675360:web:c3179dcec5b8695d9b7bc5',
    messagingSenderId: '599314675360',
    projectId: 'edupass-9e2ba',
    authDomain: 'edupass-9e2ba.firebaseapp.com',
    storageBucket: 'edupass-9e2ba.firebasestorage.app',
    measurementId: 'G-BC21VBK1JE',
  );
}
